#---------------------------------------------
#               THE LOCATION
#---------------------------------------------
broadcast: '&b坐标广播 &6&o>> &a%p的坐标: X:%x Y:%y Z:%z 世界:%w'
#可以不写%p,&y,虽然其他的也可以不写....但是强力推荐保留%p,%x,%z
#%p:玩家名 %x:X轴 %y:Y轴 %z:Z轴 %w:世界名
bc_Success: '&b发送成功'
#%p 玩家名字
